repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v5.0.0
  hooks:
  - id: end-of-file-fixer
    exclude: (.txt$|.ipynb$)
  - id: trailing-whitespace
    exclude: (.txt$|README.md$)
  - id: check-yaml
  - id: check-json
  - id: check-toml
  - id: detect-private-key
  - id: check-case-conflict
  - id: check-symlinks
  - id: check-docstring-first
  - id: mixed-line-ending
  - id: destroyed-symlinks
  - id: debug-statements
  - id: pretty-format-json
    args: [--autofix]
    exclude: (\.ipynb$|package-lock.json$|package.json$)

- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.1.13
  hooks:
  - id: ruff
    args: [--fix, --exit-non-zero-on-fix]

- repo: https://github.com/psf/black
  rev: 23.12.1
  hooks:
  - id: black
    args: [--config=pyproject.toml]


- repo: https://github.com/macisamuele/language-formatters-pre-commit-hooks
  rev: v2.12.0
  hooks:
  - id: pretty-format-yaml
    args: [--autofix]
    exclude: (dependabot.yml$)
  - id: pretty-format-toml
    args: [--autofix]
    exclude: (^poetry.lock$)


- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.8.0
  hooks:
  - id: mypy
    args:
    - --explicit-package-bases
    - --ignore-missing-imports
    additional_dependencies:
    - types-requests

- repo: https://github.com/python-poetry/poetry
  rev: 1.7.0
  hooks:
  - id: poetry-check
  - id: poetry-install

- repo: https://github.com/python-jsonschema/check-jsonschema
  rev: 0.27.3
  hooks:
  - id: check-github-workflows

- repo: https://github.com/MarcoGorelli/auto-walrus
  rev: v0.2.2
  hooks:
  - id: auto-walrus
