name: Code Quality

on: [push, pull_request]

jobs:
  code_quality:
    runs-on: ubuntu-24.04

    steps:
    - name: 🚚 Checkout code
      uses: actions/checkout@v6

    - name: 🐍 Set up Python 3.12
      uses: actions/setup-python@v7
      with:
        python-version: 3.12

    - name: 📦 Install Poetry
      run: |
        curl -sSL https://install.python-poetry.org | python3 -

    - name: 📥 Install dependencies
      run: |
        poetry install

    - name: ✅ Run pre-commit hooks
      run: |
        poetry run pre-commit run --all-files
